var quotes = {
    quote1: "Some day you will be old enough to start reading fairy tales again - C.S. Lewis", 
    quote2: "I think we are all well advised to keep on nodding terms with the people we used to be, whether we find them attractive company or not. ― Joan Didion", 
    quote3: "We are always the same age inside. Gertrude Stein", 
    quote4: "I am convinced that most people do not grow up. We marry and dare to have children and call that growing up. I think what we do is mostly grow old. We carry accumulation of years in our bodies, and on our faces, but generally our real selves, the children inside, are innocent and shy as magnolias. ― Maya Angelou", 
    quote5: "There is a certain part of all of us that lives outside time. Perhaps we become aware of our age only at exceptional moments and most of the time we are ageless. -Milan Kundera", 
    quote6: "The afternoon knows what the morning never suspected. - Robert Frost", 
    quote7: "Age has no reality except in the physical world. The essence of a human being is resistant to the passage of time. Our inner lives are eternal, which is to say that our spirits remain as youthful and vigorous as when we were in full bloom. ― Gabriel Garcia Marquez", 
    quote8: "She is one of those ladies who is more beautiful at sixty than she could possibly have been at twenty. (how I hope someone says that about me someday)! ― Mary Ann Shaffer", 
    quote9: "Grow old with me! The best is yet to be” ― Robert Browning", 
    quote10: "I wear my wrinkles like battle scars, having earned every last one slaying life’s dragons. They boast of my victories and some defeats while their beauty is a wealth of wisdom gained. ― Richelle E. Goodrich", 
    quote11: "The longer I live the more beautiful life becomes. ― Frank Lloyd Wright", 
    quote12: "We don't stop playing because we grow old, we grow old because we stop playing. ― George Bernard Shaw", 
    quote13: "Old age is an excellent time for outrage. My goal is to say or do at least one outrageous thing every week. ― Maggie Kuhn", 
    quote14: "Getting old is like climbing a mountain; you get a little out of breath, but the view is much better! ― Ingrid Bergman", 
    quote15: "I have reached an age when, if someone tells me to wear socks, I don’t have to. ― Albert Einstein", 
    quote16: "There is a fountain of youth: it is your mind, your talents, the creativity you bring to your life and the lives of people you love. When you learn to tap this source, you will truly have defeated age. ― Sophia Loren", 
    quote17: "Ageing is not lost youth but a new stage of opportunity and strength. -― Betty Friedan", 
    quote18: "Don’t waste so much time worrying about your skin or your weight. Develop what you do, what you put your hands on in the world. ― Meryl Streep", 
    quote19: "...inside every old person is a young person wondering what happened. ― Terry Pratchett, Moving Pictures", 
    quote20: "I think people would live a bit longer if they didn't know how old they were. Age puts restrictions on things. ― Karl Pilkington", 
    quote21: "One loses, as one grows older, something of the lightness of one's dreams; one begins to take life up in both hands, and to care more for the fruit than the flower, and that is no great loss perhaps. ― W.B. Yeats", 
    quote22: "If I could get back my youth, I'd do anything in the world except get up early, take exercise or be respectable. ― Oscar Wilde", 
    quote23: "... forty's nothing, at fifty you're in your prime, sixty's the new forty, and so on. ― Julian Barne", 
    quote24: "The secret of genius is to carry the spirit of the child into old age, which means never losing your enthusiasm. ― Aldous Huxley", 
    quote25: "When grace is joined with wrinkles, it is adorable. There is an unspeakable dawn in happy old age. ― Victor Hugo", 
    quote26: "Childhood itself is scarcely more lovely than a cheerful, kind, sunshiny old age. ― Lydia Maria Child ", 
    quote27: "I had to wait 110 years to become famous.  I wanted to enjoy it as long as possible. ― Jeanne Louise Calment", 
    quote28: "Too many people, when they get old, think that they have to live by the calendar. ― John Glenn", 
    quote29: "How old would you be if you didn't know how old you was? ― Satchel Paige", 
    quote30: "Nature gives you the face you have at twenty; it is up to you to merit the face you have at fifty.― Coco Chanel"
}

module.exports = quotes; 